name: Deploy Plane App to EC2

on:
  push:
    branches:
      - development  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install

      - name: Install PM2
        run: npm install pm2 -g
        

        
      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Your EC2 instance host/IP
          username: ${{ secrets.EC2_USERNAME }}  # SSH username for EC2
          key: ${{ secrets.EC2_SSH_KEY }}  # SSH private key for authentication
        
          script: |
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v20.12.2/bin
            cd /home/ubuntu/PLANE-UI/DEV/cs-plane-ui
            git pull origin development   
            sudo systemctl restart nginx  # Restart nginx server
            pm2 restart plane-dev   # restart pm2
   







 